import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

# Function to calculate fair value using DCF
def calculate_fair_value(fcf, growth_rate, discount_rate, terminal_growth_rate, years=5):
    fcf_list = [fcf * (1 + growth_rate)**i for i in range(1, years + 1)]
    terminal_value = fcf_list[-1] * (1 + terminal_growth_rate) / (discount_rate - terminal_growth_rate)
    discounted_fcf = [fcf / (1 + discount_rate)**i for i, fcf in enumerate(fcf_list, start=1)]
    discounted_terminal_value = terminal_value / (1 + discount_rate)**years
    fair_value = sum(discounted_fcf) + discounted_terminal_value
    return fair_value

# Streamlit interface
st.title('Enhanced Stock Fair Value Calculator')

ticker = st.text_input('Enter stock ticker', 'AAPL')
if ticker:
    stock = yf.Ticker(ticker)
    info = stock.info
    
    st.subheader(f'{info["shortName"]} ({ticker})')
    
    # Display key metrics
    st.write(f'**Current Price:** {info["currentPrice"]}')
    st.write(f'**Market Cap:** {info["marketCap"]/1000000000}Billion')
    st.write(f'**P/E Ratio:** {info["trailingPE"]}')
    
    # Historical data
    st.subheader('Historical Data')
    hist = stock.history(period='5y')
    st.line_chart(hist['Close'])
    
    # Financials
    st.subheader('Financials')
    financials = stock.financials.transpose()
    st.write(financials)

        # Explanation of Inputs
    st.subheader('Explanation of Inputs for DCF')
    st.markdown("""
    **Free Cash Flow (FCF):** This is the cash generated by the company after accounting for capital expenditures. It is a measure of financial performance that shows how much cash a company generates from its operations.
    
    **Growth Rate:** This is the annual rate at which the company's free cash flow is expected to grow. Historical growth rates, industry trends, and company-specific factors should be considered to estimate this.
    
    **Discount Rate:** This rate is used to discount future cash flows to their present value. It reflects the riskiness of the investment and is often represented by the company's Weighted Average Cost of Capital (WACC).
    
    **Terminal Growth Rate:** This is the perpetual growth rate of the company’s free cash flow after the projection period. It is typically aligned with the long-term growth rate of the economy or inflation.
    
    **Impact on Valuation:**
    - **Higher FCF** leads to a higher valuation as it indicates more cash generation.
    - **Higher Growth Rate** increases the valuation as future cash flows are expected to be higher.
    - **Higher Discount Rate** reduces the valuation as it implies greater risk and reduces the present value of future cash flows.
    - **Higher Terminal Growth Rate** increases the terminal value, thereby increasing the overall valuation.
    """)
    
    # User assumptions
    st.subheader('User Assumptions for DCF')
    fcf = st.number_input('Current Free Cash Flow (in billions)', value=info['freeCashflow'] / 1e9)
    growth_rate = st.slider('FCF Growth Rate (annual %)', 0, 30, 10) / 100
    discount_rate = st.slider('Discount Rate (%)', 0, 15, 9) / 100
    terminal_growth_rate = st.slider('Terminal Growth Rate (%)', 0, 5, 3) / 100

    if st.button('Calculate Fair Value'):
        fair_value = calculate_fair_value(fcf, growth_rate, discount_rate, terminal_growth_rate)
        fair_value_per_share = fair_value*1000000000 / info['sharesOutstanding']
        st.write(f'**Calculated Fair Value:** ${fair_value:.2f} billion')
        st.write(f'**Fair Value per Share:** ${fair_value_per_share:.2f}')
